import os

cwd = os.getcwd() + os.sep + "preprocess" + os.sep
indir = f"{cwd}input{os.sep}"
outdir = f"{cwd}out{os.sep}"
interimdir = f"{cwd}interim{os.sep}"

no_plenary_sessions = 8
no_special_sessions = 29
no_technical_sessions = 16
no_sessions = no_plenary_sessions + no_special_sessions + no_technical_sessions

min_talks = no_plenary_sessions+ no_special_sessions*3 + no_technical_sessions*3
max_talks = no_plenary_sessions+ no_special_sessions*4 + no_technical_sessions*4
max_organizers = no_special_sessions
max_organizers = no_special_sessions * 3

# dictionary describing all Google Sheets and their columns to be selected
gsheets = {
    "schedule": {
        "sheet_id": "1GR7LoeFuSbpomrHPnWqR9soJVkIkh56AAbAGx5zQGr4",
        "sheet_name": "Form Responses 1",
        "columns": None
    },
    "plenary_abstracts": {
        "sheet_id": "1xNO88DO2COTkJ1vOzCXQiTrxKa7_pxW3a2yU06JoDEY",
        "sheet_name": "Form Responses 1",
        "columns": [
            "First or given name(s) of presenter", "Last or family name of presenter",
            "Institution of presenter", #"Email of presenter", 
            "Talk Title",
            "FirstNameLastNameAbstract.tex file with Talk Title and Abstract"
        ]
    },
    "special_session_submissions": {
        "sheet_id": "1i6OUgAZSI_evTy0E8X5NUB0IzGwLIjwtu_cSnGwl960",
        "sheet_name": "Form Responses 1",
        "columns": [
            "First or given name(s) of first organizer", "Last or family name(s) of first organizer",
            "Institution of first organizer", #"Email of first organizer",
            "First or given name(s) of second organizer", "Last or family name(s) of second organizer",
            "Institution of second organizer",
            "First or given name(s) of third organizer", "Last or family name(s) of third organizer",
            "Institution of third organizer",
            "Presenter 1 first or given name(s)", "Presenter 1 last or family name(s)",
            "Presenter 1 institution", "Presenter 1 email", 
            "Presenter 2 first or given name(s)", "Presenter 2 last or family name(s)",
            "Presenter 2 institution", "Presenter 2 email",
            "Presenter 3 first or given name(s)", "Presenter 3 last or family name(s)",
            "Presenter 3 institution", "Presenter 3 email",
            "Presenter 4 first or given name(s)", "Presenter 4 last or family name(s)",
            "Presenter 4 institution", "Presenter 4 email",
            "Session Title",
            "FirstNameLastNameSession.tex file with Session Title and Description"
        ]
    },
    "special_session_abstracts": {
        "sheet_id": "10o80tZl1f5XGXT4WpqYe7v4nzzFyBEvgUYxDAkT5LlI",
        "sheet_name": "Form Responses 1",
        "columns": [
            "First or given name(s) of presenter", "Last or family name of presenter",
            "Institution of presenter", #"Email of presenter", 
            "Talk Title",
            "FirstNameLastNameAbstract.tex file with Talk Title and Abstract", 
            "Special Session Title",
            "Include"
        ]
    },
    "contributed_talk_submissions": {
        "sheet_id": "1o1WeviV-MTGQMFHqsiAkZwMVOO0_h3GNekgCS2fojGM",
        "sheet_name": "Form Responses 1",
        "columns": [
            "First or given name(s) of presenter", "Last or family name of presenter",
            "Institution of presenter", #"Email of presenter", 
            "Talk Title", "SESSION", "Topic",
            "FirstNameLastNameAbstract.tex file with Talk Title and Abstract", 
            "Acceptance"
        ]
    }
}
 
# Map for organizations:
org_dict = {
        "Ensae":"ENSAE",
        "Academy of Mathematics and Systems Science, Chinese Academy of Sciences": "Chinese Academy of Sciences",
        "Work done during C. Huang's Ph.D. studies at Georgia Institute of Technology": "Georgia Institute of Technology",
        "INESC-ID, Rua Alves Redol 9, Lisbon, Portugal 1000-029": "INESC-ID",
        "Department of Mathematical Sciences, Tsinghua University": "Tsinghua University",
        "Illinois Institute of Technology, Department of Applied Mathematics. Sandia National Laboratories.": "Illinois Institute of Technology and Sandia National Laboratories.",
        "Department of Statistics, Columbia University": "Columbia University",
        "Department of Mathematics, Univeristy of Washington": "University of Washington",
        "KAUST: King Abdullah University of Science and Technology (KAUST)": "King Abdullah University of Science and Technology",
        "Istituto Nazionale di Fisica Nucleare (INFN), Laboratori Nazionali del Sud (LNS), Catania, Italy": "Laboratori Nazionali del Sud",
        "Chair of Mathematics for Uncertainty Quantification, Department of Mathematics, RWTH- Aachen University": "RWTH Aachen University",
        "Rwth--Aachen": "RWTH Aachen",
        "Rwth": "RWTH",
        "rwth": "RWTH",
        "Mit": "MIT",
        "Oden Institute for Computational Engineering and Sciences, University of Texas at Austin": "University of Texas at Austin",
        "Ricam, Austrian Academy of Sciences": "Austrian Academy of Sciences",
        "Archimedes/athena Research Centre": "Athena Research Centre",
        "Bcam - Basque Center for Applied Mathematics": "Basque Center for Applied Mathematics",
        "Comsats University Islamabad-Lahore": "COMSATS University Islamabad, Lahore",
        "Ensae Paris": "ENSAE Paris",
        "Institute of Mathematics, Epfl": "EPFL",
        "Epfl": "EPFL",
        "Eth Zurich": "ETH Zurich",
        "Fu Berlin": "Free University of Berlin",
        "Ibm Research": "IBM Research",
        "Ku Leuven": "KU Leuven",
        "Illinois Tech": "Illinois Institute of Technology",
        "King Abdullah University of Science and Technology (kaust)": "King Abdullah University of Science and Technology",
        "Kaust": "King Abdullah University of Science and Technology",
        "University of Warwick, Uk": "University of Warwick",
        "Uc Berkeley": "University of California, Berkeley",
        "The University of Tokyo": "University of Tokyo",
        "Tu Bergakademie Freiberg": "TU Bergakademie Freiberg",
        ", Shanghai, China": "",
        ", Sweden": "",
        ", Brazil": "",
        "Kth ": "KTH ",
        ", Uk": "",
        "Infn": "INFN",
        "infn": "INFN",
        "Lut University":"LUT University",
        "Courant Institute of Mathematical Sciences, ":"",
        ", Laboratori Nazionali del Sud (lns), Catania, Italy":"",
        ", Kaohsiung, Taiwan":"",
        "Institute of Statistics, ":"",
        "Rptu ": "RPTU ",
        ", Institut de Mathématiques de Bordeaux":"",
        "University of Maryland Baltimore County":"University of Maryland, Baltimore",
        "MIT":"Massachusetts Institute of Technology",
        "Mgimo Tashkent Branch":"MGIMO, Tashkent",
        " - Section of Catania": " Catania",
        "Inesc-Id, Rua Alves Redol 9, Lisbon, Portugal 1000-029":"INESC-ID"
    }

short_org_dict = {
    'Aalto University': 'Aalto, FIN',
    'Athena Research Centre': 'ARC, GRC',
    'Austrian Academy of Sciences': 'OeAW, AUT',
    'Basque Center for Applied Mathematics': 'BCAM, ESP',
    'Belgian Military Academy': 'BMA, BEL',
    'Bocconi University': 'Bocconi, ITA',
    'COMSATS University Islamabad, Lahore': 'COMSATS, PAK',
    'Carnegie Mellon University': 'CMU, USA',
    'Chalmers Institute of Technology': 'Chalmers, SWE',
    'Chalmers University of Technology and University of Gothenburg': 'Chalmers, SWE and GU, SWE',
    'Chemnitz University of Technology': 'Chemnitz, DEU',
    'Chinese Academy of Sciences': 'CAS, CHN',
    'Columbia University': 'Columbia, USA',
    'Cornell University': 'Cornell, USA',
    'Duke University': 'Duke, USA',
    'Durham University': 'Durham, GBR',
    'ENSAE Paris': 'ENSAE, FRA',
    'EPFL': 'EPFL, CHE',
    'ETH Zurich': 'ETH, CHE',
    'Ensae, Institut Polytechnique de Paris': 'ENSAE, FRA',
    'Fermi National Accelerator Laboratory': 'Fermilab, USA',
    'Fermilab': 'Fermilab, USA',
    'Flatiron Institute': 'Flatiron, USA',
    'Florida State University': 'FSU, USA',
    'Florida State University and National Institute of Standards and Technology': 'FSU, USA and NIST, USA',
    'Free University of Berlin': 'FU Berlin, DEU',
    'Friedrich Schiller University Jena': 'FSU Jena, DEU',
    'Georgia Institute of Technology': 'Georgia Tech, USA',
    'Gwangju Institute of Science and Technology': 'GIST, KOR',
    'Heidelberg University': 'Heidelberg, DEU',
    'Heriot-Watt University': 'Heriot-Watt, GBR',
    'Hun-Ren Alfréd Rényi Institute of Mathematics': 'Rényi Institute, HUN',
    'IBM Research': 'IBM, USA',
    'INESC-ID': 'INESC-ID, PRT',
    'INFN Catania': 'INFN Catania, ITA',
    'Illinois Institute of Technology': 'IIT, USA',
    'Impa, Rio de Janeiro': 'IMPA, BRA',
    'Inria': 'Inria, FRA',
    'Istituto Nazionale di Fisica Nucleare (INFN)': 'INFN, ITA',
    'Johann Radon Institute for Computational and Applied Mathematics': 'RICAM, AUT',
    'KTH Royal Institute of Technology': 'KTH, SWE',
    'KU Leuven': 'KU Leuven, BEL',
    'Karlsruhe Institute of Technology': 'KIT, DEU',
    'King Abdullah University of Science and Technology': 'KAUST, SAU',
    'King Abdullah University of Science and Technology/RWTH Aachen University': 'KAUST, SAU and RWTH, DEU',
    'Kuleuven & Unife': 'KU Leuven, BEL and Unife, ITA',
    'LUT University': 'LUT, FIN',
    'MGIMO, Tashkent': 'MGIMO, UZB',
    'Massachusetts Institute of Technology': 'MIT, USA',
    'Max Planck Institute for Informatics': 'MPI-INF, DEU',
    'Michigan State University': 'MSU, USA',
    'Microsoft Research New England': 'MSR New England, USA',
    'National University of Kaohsiung': 'NUK, TWN',
    'New York University': 'NYU, USA',
    'North Carolina State University': 'NC State, USA',
    'Northwestern University': 'Northwestern, USA',
    'Nvidia Corporation': 'Nvidia, USA',
    'Osnabruck University': 'UOS, DEU',
    'Paris 1 Pantheon-Sorbonne University': 'Paris1, FRA',
    'Purdue University': 'Purdue, USA',
    'Queen Mary University of London': 'QMUL, GBR',
    'Queen\'s University': 'Queen\'s, GBR',
    'RPTU Kaiserslautern-Landau': 'RPTU, DEU',
    'RWTH Aachen University': 'RWTH, DEU',
    'Rancho Bernardo High School': 'RBHS, USA',
    'Rosenheim Technical University of Applied Sciences': 'TH Rosenheim, DEU',
    'Ruhr West University of Applied Sciences': 'RWU, DEU',
    'Rutgers University': 'Rutgers, USA',
    'Sandia National Laboratories': 'Sandia, USA',
    'Shanghai Jiao Tong University': 'SJTU, CHN',
    'South China University of Technology': 'SCUT, CHN',
    'Southern Methodist University': 'SMU, USA',
    'Stanford University': 'Stanford, USA',
    'Suqian University': 'Suqian, CHN',
    'TU Bergakademie Freiberg': 'TUBAF, DEU',
    'Tsinghua University': 'Tsinghua, CHN',
    'Universidad Adolfo Ibáñez': 'UAI, CHL',
    'Universite de Montreal': 'UdeM, CAN',
    'University of Amsterdam': 'UvA, NLD',
    'University of Augsburg': 'UA, DEU',
    'University of Bonn': 'UBonn, DEU',
    'University of British Columbia': 'UBC, CAN',
    'University of California, Berkeley': 'UC Berkeley, USA',
    'University of California, Davis': 'UC Davis, USA',
    'University of California, Santa Barbara': 'UCSB, USA',
    'University of Cambridge': 'Cambridge, GBR',
    'University of Chicago': 'UChicago, USA',
    'University of Copenhagen': 'UCPH, DNK',
    'University of Edinburgh': 'Edinburgh, GBR',
    'University of Graz': 'Uni Graz, AUT',
    'University of Heidelberg': 'Heidelberg, DEU',
    'University of Jyvaskyla': 'JYU, FIN',
    'University of Kansas': 'KU, USA',
    'University of Kentucky': 'UKY, USA',
    'University of Klagenfurt': 'AAU, AUT',
    'University of Leeds': 'Leeds, GBR',
    'University of Leoben': 'MUL, AUT',
    'University of Mannheim': 'UMannheim, DEU',
    'University of Maryland, Baltimore': 'UMB, USA',
    'University of Massachusetts Amherst': 'UMass Amherst, USA',
    'University of Michigan': 'UMich, USA',
    'University of Michigan, Ann Arbor': 'UMich, USA',
    'University of Montréal': 'UdeM, CAN',
    'University of New South Wales': 'UNSW, AUS',
    'University of Notre Dame': 'Notre Dame, USA',
    'University of Oslo': 'UiO, NOR',
    'University of Osnabrück': 'UOS, DEU',
    'University of Oxford': 'Oxford, GBR',
    'University of Passau': 'UPASS, DEU',
    'University of Pennsylvania': 'UPenn, USA',
    'University of Southern California': 'USC, USA',
    'University of Texas at Austin': 'UT Austin, USA',
    'University of Tokyo': 'UTokyo, JPN',
    'University of Toronto': 'UofT, CAN',
    'University of Warsaw': 'UW, POL',
    'University of Warwick': 'Warwick, GBR',
    'University of Washington': 'UW, USA',
    'University of Waterloo': 'UW, CAN',
    'University of World Economy and Diplomacy': 'UWED, UZB',
    'University of the West of England': 'UWE, GBR',
    'Université Paris 1 Panthéon Sorbonne': 'Paris1, FRA',
    'Université de Bordeaux': 'UBx, FRA',
    'Utrecht University': 'Utrecht, NLD',
    'Virginia Tech': 'VT, USA',
    'Yale University': 'Yale, USA',
    'Yamagata University': 'Yamagata, JPN',
}
